### ISSUE TITLE
I cannot build infer v1.0.0 from source code on OSX even I followed the official instructions

### ISSUE THREAD

**Issue by ZilinXiang** [facebook/infer#1370]
```
- infer-version: v1.0.0
- operating system: macOS Catalina 10.15.7
- command: ./build-infer.sh clang
```
The following is the relative error in the output:
```
CMake Error at test/builtins/CMakeLists.txt:55 (message):
  Target clang_rt.builtins_arm64_osx does not exist


-- Configuring incomplete, errors occurred!
See also "/tmp/clang-setup.vJi3U3/build/tools/clang/runtime/compiler-rt-bins/CMakeFiles/CMakeOutput.log".
See also "/tmp/clang-setup.vJi3U3/build/tools/clang/runtime/compiler-rt-bins/CMakeFiles/CMakeError.log".
[3601/3606] Linking CXX executable bin/clang-scan-deps
FAILED: tools/clang/runtime/compiler-rt-stamps/compiler-rt-configure
cd /tmp/clang-setup.vJi3U3/build/tools/clang/runtime/compiler-rt-bins && /usr/local/Cellar/cmake/3.19.1/bin/cmake -DCMAKE_C_COMPILER=/tmp/clang-setup.vJi3U3/build/./bin/clang -DCMAKE_CXX_COMPILER=/tmp/clang-setup.vJi3U3/build/./bin/clang++ -DCMAKE_BUILD_TYPE=Release -DCMAKE_MAKE_PROGRAM=/usr/local/bin/ninja -DLLVM_CONFIG_PATH=/tmp/clang-setup.vJi3U3/build/./bin/llvm-config -DLLVM_LIT_ARGS=-sv -DCOMPILER_RT_OUTPUT_DIR=/tmp/clang-setup.vJi3U3/build/./lib/clang/10.0.1 -DCOMPILER_RT_EXEC_OUTPUT_DIR=/tmp/clang-setup.vJi3U3/build/./bin -DCOMPILER_RT_INSTALL_PATH:STRING=lib/clang/10.0.1 -DCOMPILER_RT_INCLUDE_TESTS=ON -DCMAKE_INSTALL_PREFIX=/Users/xxxx/infer/facebook-clang-plugins/clang/install -DLLVM_LIBDIR_SUFFIX= -DLLVM_RUNTIME_OUTPUT_INTDIR=/tmp/clang-setup.vJi3U3/build/./bin -DCMAKE_OSX_DEPLOYMENT_TARGET= -DCMAKE_OSX_SYSROOT:PATH=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk -DCOMPILER_RT_PREFIX=/tmp/clang-setup.vJi3U3/build/projects/compiler-rt -DCOMPILER_RT_SRC_ROOT=/Users/xxxx/infer/facebook-clang-plugins/clang/src/download/llvm/projects/compiler-rt -GNinja /Users/xxxx/infer/facebook-clang-plugins/clang/src/download/llvm/projects/compiler-rt && /usr/local/Cellar/cmake/3.19.1/bin/cmake -E touch /tmp/clang-setup.vJi3U3/build/tools/clang/runtime/compiler-rt-stamps//compiler-rt-configure
ninja: build stopped: subcommand failed.
make[1]: *** [clang_setup] Error 1
make: *** [opt] Error 2

  compilation failure; you can try running

    make clean
    './build-infer.sh' clang
```
Where is wrong ?

**Comment by ZilinXiang** [comment]
I build infer from the source code (latest main branch in git repository), and I also tried to build infer from the release source code, I get a different error. 
```
[3422/3425] Performing build step for 'compiler-rt'
[49/5179] Building CXX object lib/sani...r/sanitizer_platform_limits_posix.cc.o
FAILED: lib/sanitizer_common/CMakeFiles/RTSanitizerCommonNoHooks.osx.dir/sanitizer_platform_limits_posix.cc.o
/tmp/clang-setup.ttjbGY/build/./bin/clang++ -DHAVE_RPC_XDR_H=0 -I/Users/xxx/infer-1.0.0/facebook-clang-plugins/clang/src/download/llvm/projects/compiler-rt/lib/sanitizer_common/.. -g -O2 -Wall -std=c++11 -Wno-unused-parameter -O3 -DNDEBUG -arch arm64 -arch x86_64 -arch x86_64h -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk  -stdlib=libc++ -mmacosx-version-min=10.9 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk -fPIC -fno-builtin -fno-exceptions -funwind-tables -fno-stack-protector -fno-sanitize=safe-stack -fvisibility=hidden -fno-lto -O3 -gline-tables-only -Wno-gnu -Wno-variadic-macros -Wno-c99-extensions -Wno-non-virtual-dtor -fno-rtti -Wframe-larger-than=570 -Wglobal-constructors -DSANITIZER_SUPPORTS_WEAK_HOOKS=0 -MD -MT lib/sanitizer_common/CMakeFiles/RTSanitizerCommonNoHooks.osx.dir/sanitizer_platform_limits_posix.cc.o -MF lib/sanitizer_common/CMakeFiles/RTSanitizerCommonNoHooks.osx.dir/sanitizer_platform_limits_posix.cc.o.d -o lib/sanitizer_common/CMakeFiles/RTSanitizerCommonNoHooks.osx.dir/sanitizer_platform_limits_posix.cc.o -c /Users/xxxx/infer-1.0.0/facebook-clang-plugins/clang/src/download/llvm/projects/compiler-rt/lib/sanitizer_common/sanitizer_platform_limits_posix.cc
/Users/xxxx/infer-1.0.0/facebook-clang-plugins/clang/src/download/llvm/projects/compiler-rt/lib/sanitizer_common/sanitizer_platform_limits_posix.cc:169:31: error: invalid application of 'sizeof' to an incomplete type 'struct stat64'
  unsigned struct_stat64_sz = sizeof(struct stat64);
                              ^     ~~~~~~~~~~~~~~~
/Users/xxxx/infer-1.0.0/facebook-clang-plugins/clang/src/download/llvm/projects/compiler-rt/lib/sanitizer_common/sanitizer_platform_limits_posix.cc:169:45: note: forward declaration of '__sanitizer::stat64'
  unsigned struct_stat64_sz = sizeof(struct stat64);
                                            ^
/Users/xxxx/infer-1.0.0/facebook-clang-plugins/clang/src/download/llvm/projects/compiler-rt/lib/sanitizer_common/sanitizer_platform_limits_posix.cc:195:33: error: invalid application of 'sizeof' to an incomplete type 'struct statfs64'
  unsigned struct_statfs64_sz = sizeof(struct statfs64);
                                ^     ~~~~~~~~~~~~~~~~~
/Users/xxxx/infer-1.0.0/facebook-clang-plugins/clang/src/download/llvm/projects/compiler-rt/lib/sanitizer_common/sanitizer_platform_limits_posix.cc:195:47: note: forward declaration of '__sanitizer::statfs64'
  unsigned struct_statfs64_sz = sizeof(struct statfs64);
                                              ^
2 errors generated.
[62/5179] Building CXX object lib/sani...mmonNoHooks.osx.dir/sanitizer_mac.cc.o
ninja: build stopped: subcommand failed.
FAILED: tools/clang/runtime/compiler-rt-stamps/compiler-rt-build
cd /tmp/clang-setup.ttjbGY/build/tools/clang/runtime/compiler-rt-bins && /usr/local/Cellar/cmake/3.19.1/bin/cmake --build . && /usr/local/Cellar/cmake/3.19.1/bin/cmake -E touch /tmp/clang-setup.ttjbGY/build/tools/clang/runtime/compiler-rt-stamps//compiler-rt-build
ninja: build stopped: subcommand failed.
make[1]: *** [clang_setup] Error 1
make: *** [opt] Error 2

  compilation failure; you can try running

    make clean
    './build-infer.sh' clang
```
The error just like @ fxcoudert encounterd. https://github.com/facebook/infer/issues/1354#issuecomment-737218141

**Comment by ZilinXiang** [comment]
@jvillard Could you give some help?

**Comment by jaiverma** [comment]
I am facing the same error. Trying to build on macOS Big Sur (11.1).
```
CMake Error at test/builtins/CMakeLists.txt:55 (message):
  Target clang_rt.builtins_arm64_osx does not exist
```

**Comment by jaiverma** [comment]
In the meantime for it to build, I'm disabling other architecture support except for `X86` when building `clang`.
```
diff --git a/facebook-clang-plugins/clang/setup.sh b/facebook-clang-plugins/clang/setup.sh
index 2ab130629..19eca2a21 100755
--- a/facebook-clang-plugins/clang/setup.sh
+++ b/facebook-clang-plugins/clang/setup.sh
@@ -164,7 +164,7 @@ CMAKE_ARGS=(
   -DLLVM_ENABLE_EH=On
   -DLLVM_ENABLE_RTTI=On
   -DLLVM_INCLUDE_DOCS=Off
-  -DLLVM_TARGETS_TO_BUILD="X86;AArch64;ARM;Mips"
+  -DLLVM_TARGETS_TO_BUILD="X86"
   -DLLVM_BUILD_EXTERNAL_COMPILER_RT=On
 )
```
This leads to a successful build.

**Comment by ZilinXiang** [comment]
Bravo! Compiling Clang is where we failed.
