### ISSUE TITLE
Failed to execute: javac -J-Duser.language=en 

### ISSUE THREAD

**Issue by shreyasmrs** [facebook/infer#608]
I got the following error when I ran infer on hello.java in the examples folder.
I'm new to SCR and couldn't figure it out. It also says 
Uncaught exception:
                                  (Unix.Exit_or_Signal(Exit_non_zero 2))

**Comment by jvillard** [comment]
Can you please provide more information? Please include:
- the version of infer you are using
- how you built/installed infer
- the command you used to run infer
- the full output (please use https://gist.github.com/ or equivalent)
- the contents of toplevel.log (also on https://gist.github.com/)

**Comment by shreyasmrs** [comment]
I pulled out the latest version of infer from github.
build ./autogen.sh
./configure
./build(something).sh

command to run
infer -- javac hello.java

Can I get the stepwise guide to install in kali linux

thanks

**Comment by jvillard** [comment]
The correct invocation for the example in the repo is `infer -- javac examples/Hello.java`, is that what you ran?

If so, could you please paste the full output of infer?

**Comment by shreyasmrs** [comment]
yes, thats right

I found the issue. I twas due to atdgen1.6.0 not installed.
I installed it using opam install atdgen=1.6.0 and still I'm having same issue

**Comment by jvillard** [comment]
Can you paste the output of `./build-infer.sh` and `infer -- javac examples/Hello.java` somewhere?

**Comment by shreyasmrs** [comment]
Uncaught exception:
(Unix.Exit_or_Signal(Exit_non_zero 2))


invoked some(around 4) .ml files

**Comment by jvillard** [comment]
I really need the full output to be able to help you further.

**Comment by shreyasmrs** [comment]
infer -- javac hello.java
Capturing in javac mode...
Failed to execute: javac -J-Duser.language=en @/tmp/args_936e26
Uncaught exception:
  
  (Unix.Exit_or_signal (Exit_non_zero 2))

Raised at file "integration/Javac.ml", line 77, characters 14-17
Called from file "src/exn.ml", line 45, characters 8-11
Re-raised at file "src/exn.ml", line 48, characters 12-15
Called from file "src/core_unix.ml", line 1002, characters 36-77
Called from file "integration/Javac.ml", line 83, characters 25-51
Called from file "backend/infer.ml", line 455, characters 2-21

**Comment by jvillard** [comment]
Try `infer -- javac examples/Hello.java`

**Comment by jvillard** [comment]
If you try the javac command that infer failed to execute (`javac -J-Duser.language=en @/tmp/args_936e26`) it will give you more info.

**Comment by shreyasmrs** [comment]
I was inside examples folder and this issue happened and now I came out of examples folder its working fine.

Thanks @jvillard

**Comment by shankybnl** [comment]
Hi,

I am getting the above-mentioned error while executing java_hello/Hello.java file. Below are the details for debugging:

- version of infer : **Infer version v0.10.0**

- how you built/installed infer: **via docker**

- the command you used to run infer: **infer -- javac Hello.java**. Also tried, **infer -- javac java_hello/Hello.java**

- java and javac version: openjdk version "1.8.0_45-internal" and javac 1.8.0_45-internal

- ./build.sh output: 
make[2]: Leaving directory '/opt/infer-linux64-v0.10.0/infer/models/c'
cd models; jar cf ../models.jar *
make[2]: Leaving directory '/opt/infer-linux64-v0.10.0/infer/models/cpp'
/usr/bin/install -c -m 644 -C models.jar /opt/infer-linux64-v0.10.0/infer/lib/java/models.jar
make[2]: Leaving directory '/opt/infer-linux64-v0.10.0/infer/models/java'
make[1]: Leaving directory '/opt/infer-linux64-v0.10.0/infer/models'



- Output of the command:
Capturing in javac mode...
Failed to execute: javac -J-Duser.language=en @/tmp/args_7cf4b4
Uncaught exception:
  
  (Unix.Exit_or_signal (Exit_non_zero 1))

Raised at file "integration/Javac.ml", line 77, characters 14-17
Called from file "src/exn.ml", line 45, characters 8-11
Re-raised at file "src/exn.ml", line 48, characters 12-15
Called from file "src/core_unix.ml", line 1002, characters 36-77
Called from file "integration/Javac.ml", line 83, characters 25-51
Called from file "backend/infer.ml", line 455, characters 2-21


Please help to resolve the issue.

**Comment by jvillard** [comment]
Does `javac Hello.java` work on its own?

**Comment by shankybnl** [comment]
@jvillard : Below is the output of `javac Hello.java`

Hello.java:22: error: package Pointers does not exist
    Pointers.A a = Pointers.mayReturnNull(10);
            ^
Hello.java:22: error: cannot find symbol
    Pointers.A a = Pointers.mayReturnNull(10);
                   ^
  symbol:   variable Pointers
  location: class Hello
Hello.java:28: error: package Pointers does not exist
    Pointers.A a = Pointers.mayReturnNull(rng.nextInt());
            ^
Hello.java:28: error: cannot find symbol
    Pointers.A a = Pointers.mayReturnNull(rng.nextInt());
                   ^
  symbol:   variable Pointers
  location: class Hello
Hello.java:34: error: cannot find symbol
    OutputStream stream = Resources.allocateResource();
                          ^
  symbol:   variable Resources
  location: class Hello
5 errors

**Comment by jvillard** [comment]
I see, you're analyzing [these files](https://github.com/facebook/infer/tree/8a8fe9eedd7fdaae1cfbdbf1cae23be2ef2792f2/examples/java_hello), sorry I missed that. You want this command (pointed out in [this README](https://github.com/facebook/infer/blob/8a8fe9eedd7fdaae1cfbdbf1cae23be2ef2792f2/examples/README.md#contents)):

```
infer -- javac Pointers.java Resources.java Hello.java
```

In general, infer needs a working compilation command to run, so if `javac` fails then so will infer. The error message should be better in the new 0.11.0 version too.

**Comment by shankybnl** [comment]
Thanks a lot @jvillard for the help! Working fine with the below command.

`infer -- javac Pointers.java Resources.java Hello.java`
