### ISSUE TITLE
infer fails with  Mangling declaration '<deduction guide for X>'

### ISSUE THREAD

**Issue by markpapadakis** [facebook/infer#1130]
On Ubuntu Linux 18.04
`infer run -- clang++ -std=c++1z a.cpp`  fails with:
```cpp
template <typename T>
struct values_repr final {
        const T s;
        const T e;

        explicit values_repr(const T a, const unsigned cnt) noexcept
            : s(a), e(a + cnt) {
        }
};

int main() {
        unsigned    v[] = {10, 20, 30, 40, 50};
        values_repr vr(0, 5);

        return 0;
}
```

[output here](https://gist.github.com/markpapadakis/3c96c0a45ed7f606c96b7b803c6b1759)

**Comment by jvillard** [comment]
What version of infer are you using?

I can't repro locally with the latest master.

```
$ infer run -- clang++ -std=c++1z bleh.cpp 
Capturing in make/cc mode...
Found 1 source file to analyze in /home/jul/tmp/infer-out


Analysis finished in 133mss

Found 1 issue

bleh.cpp:13: error: DEAD_STORE
  The value written to &vr (type values_repr<int>*) is never used.
  11.   int main() {
  12.           unsigned    v[] = {10, 20, 30, 40, 50};
  13. >         values_repr vr(0, 5);
  14.   
  15.           return 0;


Summary of the reports

  DEAD_STORE: 1
```

**Comment by markpapadakis** [comment]
```shell
./clang++ -v
clang version 8.0.0 (tags/RELEASE_800/final)
```

**Comment by jvillard** [comment]
What's your `infer --version`?

**Comment by markpapadakis** [comment]
0.16.0

**Comment by Hailios** [comment]
I also hit this issue.  `2.[ 0.3s/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/array:244:5: Mangling declaration 'std::<deduction guide for array>'`

here is a small reproducer:
`#include <array>
constexpr std::array array_to_be_deduced{1};
int main(){}`

I ran Infer like this: `/tmp/test_folder$ infer run --compilation-database test_compile_commands.json`

$ cat test_compile_commands.json
[
{
  "directory": "/tmp/test_folder",
  "command": "/usr/bin/clang++  -std=gnu++17 -o /tmp/test_folder/test.cpp.o -c /tmp/test_folder/test.cpp",
  "file": "/tmp/test_folder/test.cpp"
}
]

`$ infer --version`
Infer version v0.17.0
Copyright 2009 - present Facebook. All Rights Reserved.

I have tried with both old and new clang, it works fine with just clang, but not with Infer.
`$ /usr/bin/clang++ --version`
clang version 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
Target: x86_64-pc-linux-gnu

**Comment by Maverobot** [comment]
I have same issue. Compiles fine with `clang-6.0` but not with `infer`.
