### ISSUE TITLE
infer 0.12.1 fails to build on macOS 10.13 (with Xcode 9)

### ISSUE THREAD

**Issue by fxcoudert** [facebook/infer#756]
The errors are the following:

```
In file included from ./CADisplayLink.h:10:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/Foundation.framework/Headers/Foundation.h:128:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSUUID.h:26:49: error: nullability specifier '_Nullable' cannot be applied to non-pointer type 'uuid_t' (aka 'unsigned char [16]')
- (instancetype)initWithUUIDBytes:(const uuid_t _Nullable)bytes;
                                                ^
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSUUID.h:29:30: error: nullability specifier '_Nonnull' cannot be applied to non-pointer type 'uuid_t' (aka 'unsigned char [16]')
- (void)getUUIDBytes:(uuid_t _Nonnull)uuid;
                             ^
```

Full logs available there: https://gist.github.com/2015050c8e547cb6308f4847059baba5

**Comment by dulmarod** [comment]
Seems like a genuine compilation error, does the standard compilation succeed?

**Comment by jvillard** [comment]
@dulmarod note that the error happens when building the infer models (inside Homebrew). Maybe the clang shipped with infer 0.12.1 is too old and it disagrees with Xcode's toolchain on the type of `uuid_t`?

**Comment by ilovezfs** [comment]
@jvillard I was unaware that infer ships its own prebuilt clang. Is there a way to use a different clang? It's against Homebrew's policies to ship prebuilt binaries.

**Comment by jvillard** [comment]
@ilovezfs infer uses a clang plugin to hook into clang and get the AST of source files from clang. A limitation of clang plugins is that they are tied to an exact version of clang, so we provide our own clang in infer. It is not be possible to use a different (version of) clang to compile or run infer.

Clang gets compiled together with infer if you grab the sources from git, except in our GitHub releases where we ship clang pre-compiled for Linux and osx (as they explicitly state). This is mostly because compiling clang takes a long time.

**Comment by ilovezfs** [comment]
@jvillard ah OK. Then we should be building the bottles from git.

**Comment by AwayQuEM** [comment]
@jvillard I downloaded the pre-compiled for osx from v0.13.0 release, and replace on my 0.12.0 infer. 
But I still get the error like above.

**Comment by Benny-iPhone** [comment]
I'm also experiencing error while inferring, (xcode 9, maxOS 10.13), failing with AppKit and Foundation

1 error generated.
While building module 'AppKit' imported from /Users/****/Desktop/*****/****/****ViewController.h:9:
While building module 'CoreData' imported from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/System/Library/Frameworks/AppKit.framework/Headers/NSPredicateEditorRowTemplate.h:13:
In file included from <module-includes>:1:
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/System/Library/Frameworks/CoreData.framework/Headers/CoreData.h:8:9: fatal error: could not build module 'Foundation'
#import <Foundation/Foundation.h>
 ~~~~~~~^
1 error generated.
9 errors generated.
In file included from /Users/***/Desktop/***/***/****ViewController.m:9:
/Users/***/Desktop/***/***/****ViewController.h:9:9: fatal error: could not build module 'AppKit'
#import <AppKit/AppKit.h>

**Comment by jvillard** [comment]
@AwayQuEM can you paste what error you get more precisely?

@Benny-iPhone can you see what clang command infer is trying to run for the file with the error in infer-out/logs? If you could share it here I can try to repro the issue locally.

**Comment by AwayQuEM** [comment]
project: `ios_hello (example in infer)`
Mac OS:`10.12.6`
Xcode：`9.0`
infer: `0.12.0`
facebook-clang-plugin: `copy from 0.13.0 release`

## command
```bash
infer -- xcodebuild -target HelloWorldApp -configuration Debug -sdk iphonesimulator > infer.log 2>&1
```

## infer log
[infer.log](https://github.com/facebook/infer/files/1418203/infer.log)

**Comment by Benny-iPhone** [comment]
Mac OS: 10.13
Xcode: 9.0.1
infer: latest
infer -- xcodebuild -target BTSD -configuration release -sdk macosx10.13

similar log to @AwayQuEM  but with warning about AppKit and Cocoa

**Comment by Benny-iPhone** [comment]
uninstall in re-install infer fixed it

**Comment by jvillard** [comment]
Thanks for all the reports. Please upgrade to infer 0.13.0 and reopen if there's still an issue.
