### ISSUE TITLE
Download failed: https://homebrew.bintray.com/bottles/infer-0.17.0_1.catalina.bottle.1.tar.gz

### ISSUE THREAD

**Issue by puyang0521** [facebook/infer#1354]
when i run : brew install infer

I got the messeage
Error: Failed to download resource "infer"
Download failed: https://homebrew.bintray.com/bottles/infer-0.17.0_1.catalina.bottle.1.tar.gz

Then i went the link，it show me : The requested path was not found.

**Comment by puyang0521** [comment]
Could anyone else give me some help, please!!!

**Comment by andrewvaughanj** [comment]
I have no idea who is responsible for these packages, but ... if you go here https://formulae.brew.sh/formula/infer#default and view the JSON for this bottle: https://formulae.brew.sh/api/formula/infer.json then all three of the packages are "dead":

- https://homebrew.bintray.com/bottles/infer-0.17.0_1.catalina.bottle.1.tar.gz

- https://homebrew.bintray.com/bottles/infer-0.17.0_1.mojave.bottle.1.tar.gz

- https://homebrew.bintray.com/bottles/infer-0.17.0_1.high_sierra.bottle.1.tar.gz

It might be best to ask here:

- https://github.com/Homebrew/homebrew-core/blob/master/Formula/infer.rb

**Comment by andrewvaughanj** [comment]
If you don't want to use Homebrew, you could use the official 1.0 release from here:

- https://github.com/facebook/infer/releases/tag/v1.0.0

(scroll to "infer-osx-v1.0.0.tar.xz")

**Comment by puyang0521** [comment]
thanks @andrewvaughanj
I have tried other ways to install infer, but I have not succeeded, so sad

**Comment by andrewvaughanj** [comment]
Are you saying the official macOS release did not work for you?

**Comment by fxcoudert** [comment]
Hi, Homebrew developer here. We are currently trying to update to 1.0.0 but it fails to build on both macOS 10.15 and 11.0, with Xcode 12:

```
/tmp/infer-20201127-95505-1iepoqx/infer-1.0.0/facebook-clang-plugins/clang/src/download/llvm/projects/compiler-rt/lib/sanitizer_common/sanitizer_platform_limits_posix.cc:169:31: error: invalid application of 'sizeof' to an incomplete type 'struct stat64'
  unsigned struct_stat64_sz = sizeof(struct stat64);
                              ^     ~~~~~~~~~~~~~~~
```

**Comment by puyang0521** [comment]
Hi @fxcoudert 
Is there any way to successfully build on both macOS 10.15 and 11.0, with Xcode 12？
Is the binary method possible?  I have tried this way, but it didn’t work. I don’t know if anyone has succeeded.
or is there anything else you can offer to help. thank you @fxcoudert very much! thank you for your reply!

**Comment by puyang0521** [comment]
I download binary version, tar xf infer-osx-v1.0.0.tar.xz, but there are only bin、lib、share three files. Is this correct?

**Comment by jvillard** [comment]
@puyang0521 the infer binary is bin/infer in the extracted archive.

**Comment by WillieWu** [comment]
> I download binary version, tar xf infer-osx-v1.0.0.tar.xz, but there are only bin、lib、share three files. Is this correct?

请问这个最后解决了吗？

**Comment by podupu** [comment]
Do brew upgrade  and install again
