### ISSUE TITLE
Build fails with OCaml 4.06: Some record fields are undefined: out_indent

### ISSUE THREAD

**Issue by tautschnig** [facebook/infer#868]
I am getting:
```
File "base/Logging.ml", line 35, characters 4-329:
Error: Some record fields are undefined: out_indent
```

According to https://caml.inria.fr/pub/docs/manual-ocaml/libref/Format.html `formatter_out_functions` indeed requires another function to be set up.

It may very well be the case that there is something else broken on my end, but at least that error seems consistent with the documentation.

**Comment by jvillard** [comment]
Only 4.05 is supported as of yet, but 4.06 support is on our wishlist.

**Comment by mbouaziz** [comment]
Also feel free to send a pull request :)
That might be the only change needed for OCaml 4.06.

**Comment by tautschnig** [comment]
Just fighting with our build system, I hope to have some patch in the next hours.

**Comment by tautschnig** [comment]
My apologies for the delay. Here's all that I had to change, but I suppose such changes would then break the build using OCaml < 4.06?!
````diff
diff --git a/infer/src/base/Logging.ml b/infer/src/base/Logging.ml
index a2768f6..76581a3 100644
--- a/infer/src/base/Logging.ml
+++ b/infer/src/base/Logging.ml
@@ -35,7 +35,8 @@ let dup_formatter fmt1 fmt2 =
     { F.out_string= (fun s p n -> out_funs1.out_string s p n ; out_funs2.out_string s p n)
     ; out_flush= (fun () -> out_funs1.out_flush () ; out_funs2.out_flush ())
     ; out_newline= (fun () -> out_funs1.out_newline () ; out_funs2.out_newline ())
-    ; out_spaces= (fun n -> out_funs1.out_spaces n ; out_funs2.out_spaces n) } ;
+    ; out_spaces= (fun n -> out_funs1.out_spaces n ; out_funs2.out_spaces n)
+    ; out_indent= (fun n -> out_funs1.out_indent n ; out_funs2.out_indent n) } ;
   f


@@ -80,8 +81,9 @@ let mk_file_formatter file_fmt category0 =
     is_newline := true
   in
   let out_spaces n = print_prefix_if_newline () ; out_functions_orig.out_spaces n in
+  let out_indent n = print_prefix_if_newline () ; out_functions_orig.out_indent n in
   F.pp_set_formatter_out_functions f
-    {F.out_string; out_flush= out_functions_orig.out_flush; out_newline; out_spaces} ;
+    {F.out_string; out_flush= out_functions_orig.out_flush; out_newline; out_spaces; out_indent} ;
   f

````

**Comment by jvillard** [comment]
Thanks for the update. If you want to submit a PR for 4.06.0, that would be much welcome! You'll need to change build-infer.sh, configure.ac, .travis.yml, and possibly opam.lock (just type `make opam.lock` once everything else is up-to-date) to replace 4.05.0+flambda with 4.06.0+flambda as well. Basically `git grep '4\.05\.0'`.

**Comment by jberdine** [comment]
We also need an update for sawja for 4.06, but that is on the way.

**Comment by tautschnig** [comment]
Yeah, Sawja needed some fixes as well. Or maybe you can get rid of Sawja? That would be one the biggest advances for us...

**Comment by jvillard** [comment]
Working on upgrading to 4.06.1 now.

**Comment by jvillard** [comment]
Fixed by 5014e7d9eb94c9ba5febab549745d91b6647e202. Thanks!
